In [1]:
import unittest
import Puzzle
import Search
import numpy as np

3
6
1
7 2 4
5 0 6
8 3 1

7 2 4
5 0 6
8 3 1

False
do we even get here
{<Search.SearchNode object at 0x7ff8c817ef28>}
made it here
ugh
zzzzz
up
[None]
fail
fail
fail
[None]
[None]
None


In [2]:
class PuzzleTest(unittest.TestCase):
    
    
    def test_Init(self):
        p = Puzzle.Puzzle()
        testone = None
        if(p.tiles == None):
            testone = True
        else:
            testone = False
            
        z = Puzzle.Puzzle(np.array([[1,2,3],[4,5,6],[7,8,0]]))
        testtwo = None
        if(z.tiles[0][0] == 1 and z.tiles[2][2] == 0):
            testtwo = True
        else:
            testtwo = False
            
        self.assertTrue(testone and testtwo)
        
    
    
    def test_Successor(self):
        p = Puzzle.Puzzle(np.array([[1,2,3],[4,5,6],[7,8,0]]))
        testnaut = (p.tiles[2][2] == 0)
        testnaut
        
        p.successor("up")
        p.successor("up")
        testone = (p.tiles[0][2] == 0)
        print("TTTTTT")
        print(testone)
        
        p.successor("down")
        p.successor("down")
        testtwo = (p.tiles[2][2] == 0)
        print("TTTTTT")
        print(testtwo)
        
        p.successor("left")
        p.successor("left")
        print(p.tiles)
        testthree = (p.tiles[2][0] == 0)
        print("TTTTTT")
        print(testthree)
        
        p.successor("right")
        p.successor("right")
        testfour = (p.tiles[2][2] == 0)
        print("TTTTTT")
        print(testfour)
        
        self.assertTrue(testnaut and testone and testtwo and testthree and testfour)
    
    
    def test_Str(self):
        z = Puzzle.Puzzle(np.array([[1,2,3],[4,5,6],[7,8,0]]))
        print(z)
        self.assertTrue(True)
    
    
    def test_Eq(self):
        test = None
        p = Puzzle.Puzzle(np.array([[1,2,3],[4,5,6],[7,8,0]]))
        
        x = Puzzle.Puzzle(np.array([[1,2,3],[4,5,6],[7,8,0]]))
        
        z = Puzzle.Puzzle(np.array([[2,2,0],[4,5,6],[7,8,0]]))
            
        if(p == x and p != z):
            test = True
        else:
            test = False
            
        self.assertTrue(test)
        
    
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)
    

...F

1 2 3
4 5 6
7 8 0

zzzzz
up
zzzzz
up
TTTTTT
False
zzzzz
down
zzzzz
down
TTTTTT
True
zzzzz
left
zzzzz
left
[[1 2 3]
 [4 5 6]
 [7 8 0]]
TTTTTT
False
zzzzz
right
zzzzz
right
TTTTTT
True



FAIL: test_Successor (__main__.PuzzleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-2-806fac3f5a8c>", line 53, in test_Successor
    self.assertTrue(testnaut and testone and testtwo and testthree and testfour)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.005s

FAILED (failures=1)


In [3]:
class SearchNodeTest:
    
    
    def testInit():
        pass
    
    
    def testChildNodeFromAction():
        pass
    
    
    def testSolution():
        pass
    
    
    def testPath():
        pass
    
    
    def testLt():
        pass
    
    
    def testEq():
        pass
    
    
    def testHash():
        pass
    
    
    def testStr():
        pass
    
    
        

In [4]:
class SearchTest:
    
    
    def testInit():
        pass
    
    
    def testSearch():
        pass
    
    
    def testReport():
        pass
    
    
    